- core/shared/src/main/scala/sttp/model/Uri.scala
Hey, thanks for a great library.
It would be great if we could provide optional values to the `Uri.param` like
```
request.
param("test", Some(testValue))
```
> Allow to provide Optional param value in Uri.param

- core/shared/src/main/scala/sttp/model/UriInterpolator.scala
- core/shared/src/test/scala/sttp/model/UriInterpolatorTests.scala
Closes #2.
This is a breaking change for those who rely on the uri interpolation to provide `http` as the default scheme.
Work required for softwaremill/sttp#396 seems to be a lot more involved, so I plan to tackle that issue in another PR.
> Make scheme required in uri interpolation

- core/shared/src/main/scala/sttp/model/Cookie.scala
Hi. Thank you for your great libraries. I've faced with cookie expires parsing issue. If you run ```CookieTest``` with ```-Duser.country=cn -Duser.language=zh``` VM parameters you will see that test for  ```"x=y; Expires=Mon, 27-Jan-2020 16:10:25 GMT"``` has failed. Thats because ```DateTimeFormatter.ofPattern(Rfc850Pattern)``` dateformatter internally will emit Locale dependant week day names. According to [rfc2616](https://tools.ietf.org/html/rfc2616#section-3.3.1) only English week day names allowed. So I think for above dateformatter locale should be setted to US locale (This fixes ```CookieTest``` for ```-Duser.country=cn -Duser.language=zh``` VM parameters )
> fixed cookie expires parsing issue

- core/jvm/src/test/scala/sttp/model/CookieTest.scala
- core/shared/src/main/scala/sttp/model/Cookie.scala
I've faced with next _expires value_ ```Thu, 01-Jan-2114 00:00:10 GMT``` It seems to look good but 01-Jan-2114 is Monday not Thursday.  Using DateTimeFormatter's parse method causes exception due wrong weekday name. I'm not sure if [standard](https://tools.ietf.org/html/rfc2616#section-3.3.1) contains explicit requrement to week day name relation to date, but above _expires value_ string is correct in sense of _expires value_ grammar. ```java.net.HttpCookie``` for that string simply doesnt parse _expires value_. There is no any exceptions in ```java.net.HttpCookie.parse```. In turn Google Chrome doesnt drop such cookie or _expires value_ .That looks logically becase weekday name is some kind of redundant information. I think Google Chrome behaviour can be considered as canonical in the …
> Handling mailformed (in respect to date) weekday names

- .gitignore
- core/shared/src/main/scala/sttp/model/Cookie.scala
Add default values for the `safeApply` and `unsafeApply` methods on
`CookieValueWithMeta` to ease usage.
Also `.gitignore` contains now entries to ignore files generated by
Bloop and Metals.
> Provide default values for `CookieValueWithMeta`

- core/src/main/scala/sttp/model/Header.scala
When adding the "Accept" header to a request it is convenient
to be able to use the defined MediaTypes rather than having
to construct the string yourself
> Add convenience .accept method to Header companion

- core/src/main/scala/sttp/model/Part.scala
Found couple of issues while fixing https://github.com/softwaremill/sttp/issues/773:
1) form-data disposition parameters' values should be enquoted
2) some HTTP servers expect `name` to be the first parameter
> Fixed form-data params encoding

- core/src/main/scala/sttp/model/internal/Rfc3986.scala
- core/src/test/scala/sttp/model/UriInterpolatorTests.scala
For such characters, the java `Char` which contains only the first 2
bytes cannot be converted to a valid string which result in a string
containing a single byte `0x3F`.
By iterating over the UTF-8 bytes instead of 2-byte characters, we can
handle all different cases, treating the allowed characters as the
single byte characters they are.
This can occur with some APIs, such as the Discord API, which requires the reaction emoji to be part of the path in URL-encoded form.
> Support encoding of 3+ UTF-8 byte characters

- core/src/main/scala/sttp/model/MediaType.scala
- core/src/main/scala/sttp/model/internal/Patterns.scala
- core/src/test/scalajvm/sttp/model/headers/AcceptsTest.scala
So, the `.2` is fixed for `q` value, but `text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2` from issue is still invalid, since single `*` is not valid in Accept header, subtype is missing
> q value regex fix

- core/src/main/scala/sttp/model/UriInterpolator.scala
- core/src/test/scala/sttp/model/UriTests.scala
> Properly parse absolute path in a relative URI when embedded as a string

- core/src/main/scala/sttp/model/Header.scala
- core/src/main/scala/sttp/model/headers/Origin.scala
Will be used by the CORS interceptor in tapir.
Btw. different sources suggest different syntax for `Origin` - [RFC-6454](https://datatracker.ietf.org/doc/html/rfc6454#section-7) says that it's a list of hosts, while [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) says that it's a single host. Since the CORS interceptor would assume a single value, I went for the simpler MDN approach.
> Add Origin and Vary headers

- benchmark/src/main/scala/sttp/model/InterpolatorBenchmark.scala
- build.sbt
- core/src/main/scala/sttp/model/UriInterpolator.scala
- core/src/main/scala/sttp/model/internal/ArrayView.scala
- core/src/main/scala/sttp/model/internal/FastCharSet.scala
- project/plugins.sbt
This is pull request for https://github.com/softwaremill/sttp-model/issues/196.
I split my pull request into three commits:
1. First commit replaces `Vector` in `UriBuilder`s by `sttp.model.internal.ArrayView`. This allows to build `Uri` using one array (without allocations many Vectors inside each `UriBuilder`)
2. Second commit replaces `Vector` in `Tokenizer`s by `java.util.ArrayList`. Again this allows to tokenize string using one or two `ArrayList`.
3. Third commit replaces `Set` by `sttp.model.internal.FastCharSet`. Call `Set.contains(char)` leads to boxing of character which is slower than call `FastCharSet.contains(char)`. In this commit I also replaced regular expressions by custom code based on `FastCharSet`. This also improved performance.
Here is results of JMH benchmarks:
``` …
```
> Improve performance of UriInterpolator

- .github/workflows/ci.yml
- core/src/main/scalanative/sttp/model/internal/idn/CIdn.scala
idn11 is not present in vcpkg's repository, which is one of the ways to static link applications with Scala Native using https://github.com/indoorvivants/sbt-vcpkg
Since idn2 is present and it's the newest version of the library, this PR updates `sttp.model.internal.idn.CIdn` to use idn2
> Update from idn11 to idn2

- core/src/main/scala/sttp/model/Header.scala
- core/src/test/scalajvm/sttp/model/HeaderTests.scala
- core/src/test/scalajvm/sttp/model/headers/CookieTest.scala
To make http4s able to parse datetime values, the formatting of these values has to be done according to rfc1123-date1 with a leading zero for single-digit dates
> "Instant" format according to rfc1123-date1

- core/src/main/scala/sttp/model/StatusCode.scala
TooEarly was missing
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
> Added TooEarly StatusCode (425) to StatusCodes trait

- core/src/main/scala/sttp/model/MediaType.scala
- core/src/main/scala/sttp/model/headers/AcceptEncoding.scala
- core/src/main/scala/sttp/model/headers/Accepts.scala
- core/src/main/scala/sttp/model/headers/AuthenticationScheme.scala
- core/src/main/scala/sttp/model/headers/ContentRange.scala
- core/src/main/scala/sttp/model/headers/Cookie.scala
- core/src/main/scala/sttp/model/headers/ETag.scala
- core/src/main/scala/sttp/model/headers/Range.scala
- core/src/main/scala/sttp/model/headers/WWWAuthenticateChallenge.scala
- core/src/main/scala/sttp/model/internal/Patterns.scala
- core/src/test/scalajvm/sttp/model/headers/AcceptsTest.scala
Currently, it is quite expensive in terms of burned CPU and eaten memory bandwidth during parsing, validation
...and serialization
This PR reduces that overheads and improves working with headers.
> More efficient working with headers

- core/src/main/scala/sttp/model/UriInterpolator.scala
I'm working on a Tapir module for [Kyo](https://github.com/getkyo/kyo/tree/main/kyo-tapir/src/main/scala/kyo) and noticed that there's some thread blocking to materialize `ClassTag`s in `UriInterpolator`. It seems a mild problem that should affect mostly benchmarks but there could be pathological scenarios with more complex routing that make it more problematic:
Cache the `ClassTag` in a local field to avoid the synchronized cache lookup. The change avoids the blocking in `UriInterpolator` but there are still other cases that arise from other collection operations:
- As an alternative users could disable the `ClassTag` cache via `-Dscala.reflect.classtag.cache.disable=true` but it could have a performance penalty.
- If there's an interest, I could explore ways to avoid the remaining …
> optimization: cache ClassTag[Token] to avoid thread blocking

- core/src/main/scala/sttp/model/ContentTypeRange.scala
- core/src/main/scala/sttp/model/MediaType.scala
- core/src/main/scala/sttp/model/headers/Accepts.scala
- core/src/test/scala/sttp/model/MediaTypeTests.scala
- core/src/test/scalajvm/sttp/model/headers/AcceptsTest.scala
> Add `otherParameters` to ContentTypeRange, update `MediaType#matches` to take into account `otherParameters`.

- core/src/main/scala/sttp/model/MediaType.scala
- core/src/test/scala/sttp/model/MediaTypeTests.scala
Follow-up to #306
cc @kamilkloch - when the range is `*/*` or `sth/*`, we don't require parameters to match. Otherwise there are problems with boundaries in multiparts (and probably others)
> Fix matching content type range parameters in presence of wildcards

- core/src/main/scala/sttp/model/MediaType.scala
On each request, Tapir uses the `toString` in `MediaType` to produce the header. In my [benchmark](https://github.com/fwbrasil/rinha-2024-q1), the instance of `MediaType` is always the same but the string has to be produced again on each request.
Make `toString` a lazy val so the value can be reused.
- Are `MediaType` meant to be singletons? If yes, we could make `toString` a `val` to avoid the lazy val volatile read. It's likely a quite small overhead, though.
> cache `MediaType.toString`

- core/src/main/scala/sttp/model/MediaType.scala
- core/src/test/scala/sttp/model/MediaTypeTests.scala
https://github.com/softwaremill/sttp-model/pull/331 changed `MediaType.toString` to become a `lazy val`, which is a breaking change. I'm seeing this issue while trying to publish a version of Tapir with the optimizations mentioned in https://github.com/softwaremill/tapir/issues/3552.
Make the `lazy val` private and keep the same `toString()` interface as before.
> fix breaking change in MediaType.toString

- core/src/main/scala/sttp/model/UriInterpolator.scala
The uri parsing has a high allocation rate of `StringBuilder` objects in `ArrayView.mkStringOpt`. The parsing happens on each incoming request and the implementation of `mkStringOpt` uses a large `StringBuilder` initialized with 128 chars. The actual strings are typically much smaller representing a single path element.
I've debugged the code and noticed that the vast majority of calls have a `valueTs` with a single path element. I've added a special case for it so `mkStringOpt` can be avoided.
- This is part of https://github.com/softwaremill/tapir/issues/3552.
- It's probably better to avoid the custom initial `StringBuilder` capacity in `mkStringOpt` since the strings seem generally small and growing the buffer is typically not too expensive. I can follow up on that if you like.
- …
> optimize uri parsing to reduce StringBuilder allocations

- core/src/main/scala/sttp/model/Header.scala
- core/src/test/scalajvm/sttp/model/HeaderTests.scala
Per https://github.com/akka/akka/issues/17714#issuecomment-112004002, 2-digit year is a valid representation and should be adjusted into the period 1970-2069.
> Fix Rfc850DatetimeFormat to handle 2-digit year

- README.md
- core/src/main/scala/sttp/model/Part.scala
- core/src/test/scala/sttp/model/PartTest.scala
Closes #317 (with additional changes required in `sttp`)
> Removed re-encoding of multipart content-disposition header values

- core/src/main/scala/sttp/model/Uri.scala
- core/src/test/scala/sttp/model/UriTests.scala
This is the first part that needs to be implemented for adding the feature described in [sttp#2497](https://github.com/softwaremill/sttp/issues/2497).
> `Uri.toStringSafe` for hiding sensitive query params

- core/src/main/scala/sttp/model/Headers.scala
- core/src/main/scala/sttp/model/headers/ContentRange.scala
- core/src/main/scala/sttp/model/headers/Host.scala
- core/src/main/scala/sttp/model/headers/Range.scala
- core/src/test/scala/sttp/model/headers/ContentRangeTest.scala
- core/src/test/scala/sttp/model/headers/RangeTest.scala
Also, comment that `Host.parseHostAndPort` drops the port silently in case of parsing errors.
> Improve range & content range parsing
